// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

/**
 * 命令执行请求
 */
export type CommandRequest = {
    command: string;
    args?: Array<(string)>;
};

/**
 * 命令执行结果
 */
export type CommandResult = {
    command: string;
    args: Array<(string)>;
    exit_code: number;
    stdout: string;
    stderr: string;
    duration_ms: number;
};

export type CredentialCategory = 'github-copilot' | 'cursor' | 'cluade-code';

export type CredentialCreate = {
    title: string;
    category?: CredentialCategory;
    pat: string;
    is_disabled?: boolean;
    node_ids?: Array<(string)>;
};

export type CredentialPublic = {
    title: string;
    category?: CredentialCategory;
    pat: string;
    is_disabled?: boolean;
    id: string;
    owner_id: string;
    created_at: string;
    updated_at: string;
    nodes?: Array<NodePublic>;
};

export type CredentialsPublic = {
    data: Array<CredentialPublic>;
    count: number;
};

export type CredentialUpdate = {
    title?: (string | null);
    category?: (CredentialCategory | null);
    pat?: (string | null);
    is_disabled?: (boolean | null);
    node_ids?: (Array<(string)> | null);
};

/**
 * Dashboard统计数据
 */
export type DashboardStats = {
    issues: IssueStats;
    nodes: NodeStats;
    projects_count: number;
    prompts_count: number;
    credentials_count: number;
    repositories_count: number;
    running_tasks: Array<RunningTask>;
};

/**
 * GitHub多仓库同步请求模型
 */
export type GitHubMultiSyncRequest = {
    repos: Array<{
        [key: string]: unknown;
    }>;
    github_token?: (string | null);
};

/**
 * GitHub同步请求模型
 */
export type GitHubSyncRequest = {
    repo_owner: string;
    repo_name: string;
    labels?: (Array<(string)> | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type IssueCreate = {
    title: string;
    description?: (string | null);
    repository_url?: (string | null);
    issue_number?: (number | null);
    status?: string;
    priority?: number;
    assigned_node_id?: (string | null);
};

export type IssuePublic = {
    title: string;
    description?: (string | null);
    repository_url?: (string | null);
    issue_number?: (number | null);
    status?: string;
    priority?: number;
    assigned_node_id?: (string | null);
    id: string;
    owner_id: string;
    created_at: string;
    updated_at: string;
    started_at?: (string | null);
    completed_at?: (string | null);
    error_message?: (string | null);
    result_branch?: (string | null);
};

export type IssuesPublic = {
    data: Array<IssuePublic>;
    count: number;
};

/**
 * Issue统计
 */
export type IssueStats = {
    pending: number;
    processing: number;
    total: number;
};

export type IssueUpdate = {
    title?: (string | null);
    description?: (string | null);
    repository_url?: (string | null);
    issue_number?: (number | null);
    status?: (string | null);
    priority?: (number | null);
    assigned_node_id?: (string | null);
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type NodeCreate = {
    name: string;
    ip: string;
    description?: (string | null);
    tags?: (string | null);
    status?: (string | null);
};

/**
 * 从节点心跳请求
 */
export type NodeHeartbeat = {
    node_id: string;
    register_key: string;
};

export type NodePublic = {
    name: string;
    ip: string;
    description?: (string | null);
    tags?: (string | null);
    status?: (string | null);
    id: string;
    last_heartbeat?: (string | null);
};

/**
 * 从节点注册请求
 */
export type NodeRegister = {
    name: string;
    host: string;
    register_key: string;
    desc?: (string | null);
    tags?: (string | null);
};

export type NodesPublic = {
    data: Array<NodePublic>;
    count: number;
};

/**
 * Node统计
 */
export type NodeStats = {
    idle: number;
    running: number;
    offline: number;
    total: number;
};

export type NodeUpdate = {
    name?: (string | null);
    ip?: (string | null);
    description?: (string | null);
    tags?: (string | null);
    status?: (string | null);
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type ProjectCreate = {
    name: string;
    description?: (string | null);
    is_active?: boolean;
    repository_urls?: (Array<(string)> | null);
};

export type ProjectPublic = {
    name: string;
    description?: (string | null);
    is_active?: boolean;
    id: string;
    owner_id: string;
    created_at: string;
    updated_at: string;
};

export type ProjectsPublic = {
    data: Array<ProjectPublic>;
    count: number;
};

export type ProjectUpdate = {
    name?: (string | null);
    description?: (string | null);
    is_active?: (boolean | null);
    repository_urls?: (Array<(string)> | null);
};

export type PromptCreate = {
    name: string;
    content: string;
    description?: (string | null);
    tags?: (string | null);
};

export type PromptPublic = {
    name: string;
    content: string;
    description?: (string | null);
    tags?: (string | null);
    id: string;
    owner_id: string;
    created_at: string;
    updated_at: string;
};

export type PromptsPublic = {
    data: Array<PromptPublic>;
    count: number;
};

export type PromptUpdate = {
    name?: (string | null);
    content?: (string | null);
    description?: (string | null);
    tags?: (string | null);
};

/**
 * 注册密钥响应
 */
export type RegistrationKeyPublic = {
    registration_key: string;
    docker_command: string;
};

/**
 * 上报分支请求模型
 */
export type ReportBranchRequest = {
    task_id: string;
    branch_name: string;
    status: string;
    error_message?: (string | null);
};

export type RepositoriesPublic = {
    data: Array<RepositoryPublic>;
    count: number;
};

export type RepositoryCreate = {
    name: string;
    url: string;
    description?: (string | null);
    is_public?: boolean;
};

export type RepositoryPublic = {
    name: string;
    url: string;
    description?: (string | null);
    is_public?: boolean;
    id: string;
    owner_id: string;
    created_at: string;
    updated_at: string;
};

export type RepositoryUpdate = {
    name?: (string | null);
    url?: (string | null);
    description?: (string | null);
    is_public?: (boolean | null);
};

/**
 * 运行中的任务
 */
export type RunningTask = {
    task_id: string;
    issue_id: string;
    issue_title: string;
    node_name: string;
    running_time: string;
    started_at: string;
};

/**
 * 启动任务请求模型
 */
export type StartTaskRequest = {
    command?: (string | null);
};

export type TaskPublic = {
    issue_id: string;
    node_id?: (string | null);
    status?: string;
    command?: (string | null);
    result_branch?: (string | null);
    error_message?: (string | null);
    id: string;
    owner_id: string;
    created_at: string;
    updated_at: string;
    started_at?: (string | null);
    completed_at?: (string | null);
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    email?: (string | null);
    full_name?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type CredentialsReadCredentialsData = {
    limit?: number;
    skip?: number;
};

export type CredentialsReadCredentialsResponse = (CredentialsPublic);

export type CredentialsCreateCredentialData = {
    requestBody: CredentialCreate;
};

export type CredentialsCreateCredentialResponse = (CredentialPublic);

export type CredentialsReadCredentialData = {
    id: string;
};

export type CredentialsReadCredentialResponse = (CredentialPublic);

export type CredentialsUpdateCredentialData = {
    id: string;
    requestBody: CredentialUpdate;
};

export type CredentialsUpdateCredentialResponse = (CredentialPublic);

export type CredentialsDeleteCredentialData = {
    id: string;
};

export type CredentialsDeleteCredentialResponse = (Message);

export type DashboardGetDashboardStatsResponse = (DashboardStats);

export type IssuesReadIssuesData = {
    limit?: number;
    skip?: number;
};

export type IssuesReadIssuesResponse = (IssuesPublic);

export type IssuesCreateIssueData = {
    requestBody: IssueCreate;
};

export type IssuesCreateIssueResponse = (IssuePublic);

export type IssuesReadIssueData = {
    id: string;
};

export type IssuesReadIssueResponse = (IssuePublic);

export type IssuesUpdateIssueData = {
    id: string;
    requestBody: IssueUpdate;
};

export type IssuesUpdateIssueResponse = (IssuePublic);

export type IssuesDeleteIssueData = {
    id: string;
};

export type IssuesDeleteIssueResponse = (Message);

export type IssuesGetNextPendingIssueResponse = (IssuePublic);

export type IssuesProcessIssueWorkflowData = {
    id: string;
    nodeId: string;
};

export type IssuesProcessIssueWorkflowResponse = (Message);

export type IssuesCommitAndPushIssueData = {
    commitMessage?: (string | null);
    id: string;
};

export type IssuesCommitAndPushIssueResponse = ({
    [key: string]: unknown;
});

export type IssuesSyncGithubIssuesData = {
    requestBody: GitHubSyncRequest;
};

export type IssuesSyncGithubIssuesResponse = ({
    [key: string]: unknown;
});

export type IssuesSyncMultipleGithubReposData = {
    requestBody: GitHubMultiSyncRequest;
};

export type IssuesSyncMultipleGithubReposResponse = ({
    [key: string]: unknown;
});

export type IssuesStartIssueTaskData = {
    id: string;
    requestBody?: (StartTaskRequest | null);
};

export type IssuesStartIssueTaskResponse = (TaskPublic);

export type IssuesReportBranchData = {
    id: string;
    requestBody: ReportBranchRequest;
};

export type IssuesReportBranchResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type NodesReadNodesData = {
    limit?: number;
    skip?: number;
};

export type NodesReadNodesResponse = (NodesPublic);

export type NodesCreateNodeData = {
    requestBody: NodeCreate;
};

export type NodesCreateNodeResponse = (NodePublic);

export type NodesGetRegistrationKeyResponse = (RegistrationKeyPublic);

export type NodesRotateRegistrationKeyResponse = (RegistrationKeyPublic);

export type NodesRegisterNodeData = {
    requestBody: NodeRegister;
};

export type NodesRegisterNodeResponse = (NodePublic);

export type NodesNodeHeartbeatData = {
    requestBody: NodeHeartbeat;
};

export type NodesNodeHeartbeatResponse = (Message);

export type NodesReadNodeData = {
    id: string;
};

export type NodesReadNodeResponse = (NodePublic);

export type NodesUpdateNodeData = {
    id: string;
    requestBody: NodeUpdate;
};

export type NodesUpdateNodeResponse = (NodePublic);

export type NodesDeleteNodeData = {
    id: string;
};

export type NodesDeleteNodeResponse = (Message);

export type NodesExecuteCommandOnNodeData = {
    id: string;
    requestBody: CommandRequest;
};

export type NodesExecuteCommandOnNodeResponse = (CommandResult);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type ProjectsReadProjectsData = {
    limit?: number;
    skip?: number;
};

export type ProjectsReadProjectsResponse = (ProjectsPublic);

export type ProjectsCreateProjectData = {
    requestBody: ProjectCreate;
};

export type ProjectsCreateProjectResponse = (ProjectPublic);

export type ProjectsReadProjectData = {
    id: string;
};

export type ProjectsReadProjectResponse = (ProjectPublic);

export type ProjectsUpdateProjectData = {
    id: string;
    requestBody: ProjectUpdate;
};

export type ProjectsUpdateProjectResponse = (ProjectPublic);

export type ProjectsDeleteProjectData = {
    id: string;
};

export type ProjectsDeleteProjectResponse = (Message);

export type PromptsReadPromptsData = {
    limit?: number;
    skip?: number;
};

export type PromptsReadPromptsResponse = (PromptsPublic);

export type PromptsCreatePromptData = {
    requestBody: PromptCreate;
};

export type PromptsCreatePromptResponse = (PromptPublic);

export type PromptsReadPromptData = {
    id: string;
};

export type PromptsReadPromptResponse = (PromptPublic);

export type PromptsUpdatePromptData = {
    id: string;
    requestBody: PromptUpdate;
};

export type PromptsUpdatePromptResponse = (PromptPublic);

export type PromptsDeletePromptData = {
    id: string;
};

export type PromptsDeletePromptResponse = (Message);

export type RepositoriesReadRepositoriesData = {
    limit?: number;
    skip?: number;
};

export type RepositoriesReadRepositoriesResponse = (RepositoriesPublic);

export type RepositoriesCreateRepositoryData = {
    requestBody: RepositoryCreate;
};

export type RepositoriesCreateRepositoryResponse = (RepositoryPublic);

export type RepositoriesReadRepositoryData = {
    id: string;
};

export type RepositoriesReadRepositoryResponse = (RepositoryPublic);

export type RepositoriesUpdateRepositoryData = {
    id: string;
    requestBody: RepositoryUpdate;
};

export type RepositoriesUpdateRepositoryResponse = (RepositoryPublic);

export type RepositoriesDeleteRepositoryData = {
    id: string;
};

export type RepositoriesDeleteRepositoryResponse = (Message);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);