"""sync_models_with_database

Revision ID: 318e2657ad46
Revises: 001_initial_schema
Create Date: 2025-11-21 17:05:33.917716

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from datetime import datetime


# revision identifiers, used by Alembic.
revision = '318e2657ad46'
down_revision = '001_initial_schema'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Create new table
    op.create_table('credentialnodelink',
        sa.Column('credential_id', sa.Uuid(), nullable=False),
        sa.Column('node_id', sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(['credential_id'], ['credential.id'], ),
        sa.ForeignKeyConstraint(['node_id'], ['node.id'], ),
        sa.PrimaryKeyConstraint('credential_id', 'node_id')
    )
    
    # 2. Drop item table
    op.drop_table('item')
    
    # 3. Update credential table
    # Create ENUM type first
    sa.Enum('GITHUB_COPILOT', 'CURSOR', 'CLUADE_CODE', name='credentialcategory').create(op.get_bind())
    # Add new columns with default values for existing rows
    op.add_column('credential', sa.Column('category', sa.Enum('GITHUB_COPILOT', 'CURSOR', 'CLUADE_CODE', name='credentialcategory'), nullable=False, server_default='GITHUB_COPILOT'))
    op.add_column('credential', sa.Column('pat', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False, server_default=''))
    op.add_column('credential', sa.Column('is_disabled', sa.Boolean(), nullable=False, server_default='false'))
    # Drop old columns
    op.drop_column('credential', 'description')
    op.drop_column('credential', 'password')
    op.drop_column('credential', 'username')
    op.drop_column('credential', 'service')
    
    # 4. Update node table
    # First, add owner_id as nullable to allow setting values
    op.add_column('node', sa.Column('owner_id', sa.Uuid(), nullable=True))
    # Set owner_id to first user's id for existing nodes (you may need to adjust this logic)
    op.execute("UPDATE node SET owner_id = (SELECT id FROM \"user\" LIMIT 1) WHERE owner_id IS NULL")
    # Now make it non-nullable
    op.alter_column('node', 'owner_id', nullable=False)
    # Add timestamp columns with server default
    op.add_column('node', sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')))
    op.add_column('node', sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')))
    # Create foreign key
    op.create_foreign_key(None, 'node', 'user', ['owner_id'], ['id'], ondelete='CASCADE')
    
    # 5. Update repository table
    op.alter_column('repository', 'url',
               existing_type=sa.VARCHAR(length=500),
               type_=sqlmodel.sql.sqltypes.AutoString(length=1023),
               existing_nullable=False)
    
    # 6. Update user table
    op.add_column('user', sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')))
    op.add_column('user', sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'updated_at')
    op.drop_column('user', 'created_at')
    op.alter_column('repository', 'url',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=1023),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)
    op.drop_constraint(None, 'node', type_='foreignkey')
    op.drop_column('node', 'updated_at')
    op.drop_column('node', 'created_at')
    op.drop_column('node', 'owner_id')
    op.add_column('credential', sa.Column('service', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('credential', sa.Column('username', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('credential', sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('credential', sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_column('credential', 'is_disabled')
    op.drop_column('credential', 'pat')
    op.drop_column('credential', 'category')
    # Drop ENUM type
    sa.Enum('GITHUB_COPILOT', 'CURSOR', 'CLUADE_CODE', name='credentialcategory').drop(op.get_bind())
    op.create_table('item',
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('owner_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], name=op.f('item_owner_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('item_pkey'))
    )
    op.drop_table('credentialnodelink')
    # ### end Alembic commands ###
